### ISSUE TITLE
Rename primary branch to main

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-auto-test#32]
We are going through all of the node.js repositories to rename the primary branch to main. Please see nodejs/node#33864 for more context.

I also don't see any references to master in githbub workflows so I don't think there should be issues with the rename.

Please let me know if there are any concerns otherwise I'll look to do the rename Friday May 4th.

**Comment by mhdawson** [comment]
Renamed, closing.

**Comment by mmarchini** [comment]
This repository is a mirror of nodejs/node used to test automation tools before merging them to NCU or nodejs/node, and as such the default branch should remain the same as the one used on nodejs/node. Sorry I didn't see this issue before. Would you mind if I revert it until we make the change on nodejs/node?
